### ISSUE TITLE
Improve player UI

### ISSUE THREAD

**Issue by whoogle** [subinps/MusicPlayer#10]
I found that if the list of queued songs is Long then every time an new song started it pings all users whoever added an song in that list.

So my suggestion is to hide the queued or playlist of song list under an button. When an user click on that button only then full list will be shown.

The UI i am suggesting is kinda look like as described below:

**Currently Playing Song**

**Songname:** Name of song
**Duration:** song total timing
**Requested_by:** username

Below this text are total 3 buttons
In first line there must be 2 buttons.

• 1st button is **Playlist** which all group members can use.
• 2nd button is **Skip** button which only sudo users can use, for non sudo users show an popup message telling "you are not allowed to use this".
These above 2 buttons must be in 1 line

• Below these there is 3rd button named **Player controls** which opens the new sub menu which contains player functions like pause/resume, stop, mute/unmute, join/leave VC, etc . This button only can be usable by sudo users.

• Do add an **Back** button on each submenu level to go back on main player menu.

**Comment by subinps** [comment]
Try
