### ISSUE TITLE
Attributeerror

### ISSUE THREAD

**Issue by devilroogan** [subinps/MusicPlayer#18]
Bro  error occer in repo in heroku 

InputGroupCall(id=self.group_call.group_call.id, access_hash=self.group_call.group_call.access_hash)
2021-08-22T09:21:48.597532+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'id'

**Comment by subinps** [comment]
The account from which you generated string session should be an admin in CHAT where you want to play music.
