### ISSUE TITLE
add auto delete old bot messages

### ISSUE THREAD

**Issue by whoogle** [subinps/MusicPlayer#6]
please add auto delete old messages by bot like when user added a new song & that song got played successfully then there is no need to show playlist.
the old playlist messages must got automatically deleted & only 1 valid playlist message always exist in the chat rather than its multiple copies. 
For example i added an song & bot shows playlist that your song added. Now after some time either that song got finished OR someone else added an new song OR someone manually trigger /playlist command then that old message should auto delete & only 1 valid & uptodate one remains in chat.

same can be done with error/info messages like it should auto delete themselves after 120secs approx.

Implementing this could reduce the bot spam alot. I want to suggest some other UI improvements too but as of now this needed much & stability matters more than features.

At last thanks for making awesome music bot.

**Comment by cidmoosa123** [comment]
Thak you for the feedback and suggestions.
Auto deleting the previous playlist before sending the old one already exist in the Playlist messages sent to LOG_GROUP. But i will implement it in request-reply also.
Refer here https://github.com/subinps/MusicPlayer/blob/master/utils.py#L92

**Comment by SubashUduwaka** [comment]
I'm getting  **(Song not found.Try inline mode.)** Error. What may be the problem.

**Comment by subinps** [comment]
Its already there for messages sent to LOG_GROUP (requested in bot PM). I will to implement the autodelete in next release

**Comment by whoogle** [comment]
@subinps facing some ffmpeg file not found error for an song in latest code commits. Search query "grandson blood water"
